### PR TITLE
File and Directory Adapters @clean returns when fails to find a key within a tag

### PR DESCRIPTION
**Pull request by melloc01**
Directory adapter to continue trying to clean all tags instead of returning on the first miss

### CODE REVIEW

**Comment by frqnck** [comment]
Hi @melloc01, hanks for pointing this out. Your fix make sense.

Do you see that specific issue when running `phpunit tests/FilesTest.php` (or `phpunit tests/DirectoryTest.php`)? If not, could you also add a test that does.

**Comment by melloc01** [comment]
Sure @frqnck, will do! = ]

**Comment by frqnck** [comment]
Hi @melloc01, hope you are well.

What is the status with your PR? Are you able to provide a test demonstrating the issue fixed by your PR?

**Comment by melloc01** [comment]
Hi @frqnck, I am, thanks, hope you are too : ] A big project started on the company, sorry about delaying it so much, will take a look at it on this weekend

**Comment by frqnck** [comment]
PR #24 implements tests to support this PR. Closing this one down.

**Pull request closed without merging**
