### PR TITLE
MongoDB - adds 'mongodb' extension (bringing PHP7 and HHVM support).

### PR DESCRIPTION
**Pull request by dimasikturbo**

### CODE REVIEW

**Comment by frqnck** [comment]
Hi @dimasikturbo, many thanks for the contribution.

There is another PR in progress https://github.com/frqnck/apix-cache/pull/14 which is very similar.

I have merge your effort into the 'mongodb' branch (https://github.com/frqnck/apix-cache/tree/mongodb) so we can work out together the testing issues and pass Travis.
Please from now on contribute directly into that branch.

**Comment by dimasikturbo** [comment]
Hi Franck,

I've seen the travis failed mainly due to the mongo php library requirement. We could solve it by removing this requirement from composer.json and install it in travis-init.sh for PHP7 only and also we would need to enable mongodb extension as it is not by default.

**Comment by frqnck** [comment]
Yes, for most part.

It is mostly fixed in the `mongodb` branch.

What's left broken is the HHVM build:
https://travis-ci.org/frqnck/apix-cache/jobs/153639185

**Comment by dimasikturbo** [comment]
Hi Franck,

Is HHVM holding you off from merging this branch into master?

**Comment by frqnck** [comment]
Hi @dimasikturbo,

The HHVM issue has been holding this branch for ages indeed. 

The last time I tried, I was going round in circle and did not find a way to run the new `mongodb` extension with HHMV under Travis. Don't really have time to look into it at the mo so for now the best might be sadly to allow HHVM to fail.

**Comment by frqnck** [comment]
This pull-request is merged in the `mongodb` branch so I am closing this pr for now.

**Pull request closed without merging**
