### PR TITLE
fix coding style issues

### PR DESCRIPTION
**Pull request by mimmi20**
I added PHP7 and tests with memcache (without the d) to the .travis.yml file. 

I also added some docblocks my IDE complained about.

### CODE REVIEW

**Comment by frqnck** [comment]
Hi mimmi20,

Thank you for the pull request (PR) -- it is much appreciated.

However, there are a few issues.You (or your IDE/editor) have mingle with trailing spaces, white spaces and indentations, etc... which resulted in changing a large number of files, i.e. unrelated added noises.

Your PR should focus on one thing only. Stylistic changes to the code and the likes should be passed in their own isolated PRs.

Please, could you fix this PR to focus to just "Adding PHP7 to Travis CI". Essentially, it looks like only `.travis.yml` and `README.md` have actually been changed.

Many thanks.

**Comment by frqnck** [comment]
I missed the *"memcache (without the d)"* -- again this should go in its own dedicated PR.

I can't see any code (and unit tests) adding actual support to "Memcache"?

**Comment by frqnck** [comment]
Note that the Memcache PHP module is inferior to the Memcached module.

Your mileage may require/impose Memcache so having a specific implementation for it would be welcome indeed.

But generally, I would strongly suggest you stick with Memcached.

**Comment by mimmi20** [comment]
I will add an other PR.

**Pull request closed without merging**
